---
- name: include_vars ░ Gather OS specific variables
  # This task gathers variables defined in OS specific files.
  #
  # Search vars in:
  #  - <distribution>_<major>.yml    # eg. CentOS_8.yml
  #  - <os_family>_<major>.yml       # eg. RedHat_8.yml
  #  - <distribution>.yml            # eg. CentOS.yml
  #  - <os_family>.yml               # eg. RedHat.yml
  #
  # If no OS specific file is found, the role will default to vars/main.yml
  #
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_facts.distribution | replace(' ','_') }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/{{ ansible_facts.distribution | replace(' ','_') }}.yml"
        - "vars/{{ ansible_facts.os_family }}.yml"
      skip: true
  tags:
    - grafana_service
    - grafana_firewall
    - grafana_install
    - grafana_configure
    - grafana_datasources
    - grafana_notifications
    - grafana_dashboards

- include_tasks: preflight.yml
  tags:
    - grafana_service
    - grafana_firewall
    - grafana_install
    - grafana_configure
    - grafana_datasources
    - grafana_notifications
    - grafana_dashboards

- include_tasks: install.yml
  tags:
    - grafana_service
    - grafana_firewall
    - grafana_install
    - grafana_configure

- include_tasks: configure.yml
  tags:
    - grafana_configure

- include_tasks: plugins.yml
  when: grafana_plugins != []
  tags:
    - grafana_configure

- name: service █ Wait for grafana to start (http/s)
  wait_for:
    host: "{{ grafana_address }}"
    port: "{{ grafana_port }}"
  when: grafana_server.protocol is undefined or grafana_server.protocol in ['http', 'https']
  tags:
    - grafana_install
    - grafana_configure
    - grafana_datasources
    - grafana_notifications
    - grafana_dashboards
    - grafana_run

- name: service █ Wait for grafana to start (socket)
  wait_for:
    path: "{{ grafana_server.socket }}"
  when: grafana_server.protocol is defined and grafana_server.protocol == 'socket'
  tags:
    - grafana_install
    - grafana_configure
    - grafana_datasources
    - grafana_notifications
    - grafana_dashboards
    - grafana_run

- include_tasks: api_keys.yml
  when: grafana_api_keys | length > 0
  tags:
    - grafana_configure
    - grafana_run

- include_tasks: datasources.yml
  when: grafana_datasources != []
  tags:
    - grafana_configure
    - grafana_datasources
    - grafana_run

- name: "grafana █ Check if there are any dashboards in local {{ grafana_dashboards_dir }}"
  become: false
  set_fact:
    found_dashboards: "{{ lookup('fileglob', grafana_dashboards_dir + '/*.json', wantlist=True) }}"
  tags:
    - grafana_configure
    - grafana_dashboards
    - grafana_run

- include_tasks: dashboards.yml
  when: grafana_dashboards | length > 0 or found_dashboards | length > 0
  tags:
    - grafana_configure
    - grafana_dashboards
    - grafana_run

- name: "service █ Manage {{ grafana_services_to_start | join(' ') }} services state"
  service:
    name: "{{ item }}"
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
    state: "{{ (start_services | bool) | ternary('started', omit) }}"
  loop: "{{ grafana_services_to_start }}"
  tags:
    - grafana_service

- name: grafana █ UI login information
  debug:
    msg:
      - '###############################################################'
      - 'Grafana is accessible now:'
      - "URL: {{ grafana_address }}:{{ grafana_port }}"
      - "- login: {{ grafana_security.admin_user }}"
      - "- password: {{ grafana_security.admin_password }}"
      - '###############################################################'
